spring:
  profiles:
    active:
  application:
    name: ${artifactId}
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test
    username: root
    password:
server:
  port: 8080
mybatis:
  mapper-locations: ['classpath:mapper/**/*.xml']

---
spring:
  profiles: logging
logback:
  log-home: /tmp/logs/${artifactId}
